In [1]:
import tensorflow as tf

print(tf.__version__)

2.12.0


In [2]:
scaler = tf.constant(2023)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=2023>

In [3]:
scaler.ndim

0

In [4]:
vector = tf.constant([2, 4, 7])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 7], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[1, 6, 7, 8],
                      [3, 6, 0, 1]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 6, 7, 8],
       [3, 6, 0, 1]], dtype=int32)>

In [7]:
matrix_1 = tf.constant([[1,6,3],
                      [3,8,1]] , tf.int64)
matrix_1

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 6, 3],
       [3, 8, 1]])>

In [8]:
matrix.ndim

2

In [9]:
tensor = tf.constant([[[1, 3, 4],
                       [3, 6, 8],
                       [4, 2, 1]],
                      [[3, 6, 8],
                       [1, 6, 9],
                       [5, 7, 2]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[1, 3, 4],
        [3, 6, 8],
        [4, 2, 1]],

       [[3, 6, 8],
        [1, 6, 9],
        [5, 7, 2]]], dtype=int32)>

In [12]:
tensor.ndim

3

In [11]:
tensor.shape[1]

3

In [ ]:
variable_vector=tf.Variable([2,5,3])
variable_vector

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 5, 3], dtype=int32)>

In [ ]:
variable_vector[0].assign(33)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([33,  5,  3], dtype=int32)>

In [ ]:
# Generate a random tensor
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(2, 3, 4))
random_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],

       [[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
        [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]],
      dtype=float32)>

In [ ]:
# The random seed
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(2,4))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(2,4))
random_1 ,random_2 ,random_1 == random_2

(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [ ]:
# Shuffel
mat = tf.constant([[2 ,4 ,6],
                   [0 ,9 ,1],
                   [32,65,98]])
shuffel = tf.random.shuffle(mat ,seed=42)
shuffel

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[32, 65, 98],
       [ 0,  9,  1],
       [ 2,  4,  6]], dtype=int32)>

In [ ]:
# numpy
import numpy as np

numbers = np.arange(90)
matrix_of_numbers = tf.constant(numbers ,shape=(3,3,10))
print(numbers,"\n\nnew one")
matrix_of_numbers

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89] 

new one


<tf.Tensor: shape=(3, 3, 10), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]]])>

In [ ]:
matrix_of_numbers.shape ,matrix_of_numbers.ndim ,tf.size(matrix_of_numbers)

(TensorShape([3, 3, 10]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=90>)

In [ ]:
matrix_of_numbers[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int64, numpy=
array([[[ 0,  1],
        [10, 11]],

       [[30, 31],
        [40, 41]]])>

In [ ]:
matrix_new = tf.constant([[11,55,88],
                          [77,22,11],])
matrix_new[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([55, 22], dtype=int32)>

In [ ]:
# Add new dimention
matrix_new1 = matrix_new[...,tf.newaxis]
matrix_new ,matrix_new1

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[11, 55, 88],
        [77, 22, 11]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
 array([[[11],
         [55],
         [88]],
 
        [[77],
         [22],
         [11]]], dtype=int32)>)

In [ ]:
matrix_new1 = matrix_new[tf.newaxis,...]
matrix_new ,matrix_new1

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[11, 55, 88],
        [77, 22, 11]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
 array([[[11, 55, 88],
         [77, 22, 11]]], dtype=int32)>)

In [ ]:
matrix_new.shape

TensorShape([2, 3])

----

In [ ]:
# Matrix mutltiplication
x =tf.constant([[1,4,2],
                [4,2,8]])
y =tf.constant([[4,4],
                [2,5],
                [6,3]])

In [ ]:
tf.matmul(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 30],
       [68, 50]], dtype=int32)>

In [ ]:
x @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 30],
       [68, 50]], dtype=int32)>

In [ ]:
x * x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1, 16,  4],
       [16,  4, 64]], dtype=int32)>

In [ ]:
# reshape function
x @ tf.reshape(x,shape=(3,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 36],
       [24, 88]], dtype=int32)>

In [ ]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 2],
       [4, 2, 8]], dtype=int32)>

In [ ]:
# transpose
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [4, 2],
       [2, 8]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(x),x)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 12, 34],
       [12, 20, 24],
       [34, 24, 68]], dtype=int32)>

In [ ]:
x ,y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 4, 2],
        [4, 2, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 4],
        [2, 5],
        [6, 3]], dtype=int32)>)

In [ ]:
tf.tensordot(x,y, axes=1) #??????

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 30],
       [68, 50]], dtype=int32)>

----

In [ ]:
# change data type
b = tf.constant([1,5,8])
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 5, 8], dtype=int32)>

In [ ]:
bnew = tf.cast(b ,dtype=tf.int16) #tf.cast use to change data type of current matrix
bnew

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 5, 8], dtype=int16)>

In [ ]:
f = tf.constant([2. ,6. ,7.])
f

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 6., 7.], dtype=float32)>

In [ ]:
f2 = tf.cast(f ,dtype=tf.float16)
f2

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([2., 6., 7.], dtype=float16)>

In [ ]:
A = tf.constant([1,8,9,3] ,dtype=tf.int64) #change data type of new matrix
A

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 8, 9, 3])>

In [ ]:
# abs value
D = tf.constant([-23 ,-76 ,11])
D

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-23, -76,  11], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([23, 76, 11], dtype=int32)>

----

In [ ]:
# find min,max,min and sum of tensor
# make random tensor
S = tf.constant(np.random.randint(1 ,100 ,size=50),shape=(5,10))
S

<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
array([[ 4, 21,  1, 85, 69, 79, 95, 41, 58, 18],
       [55, 39, 71, 61, 16, 96, 39, 81, 56, 79],
       [67, 18,  9, 83, 38,  7, 55, 91, 12, 99],
       [97, 45, 77, 56, 41,  9, 78, 88, 23, 85],
       [ 2, 81, 97, 43, 27, 23, 98, 37, 14, 81]])>

In [ ]:
# find the min
tf.reduce_min(S)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# find the max
tf.reduce_max(S)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#find the mean
tf.reduce_mean(S)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [ ]:
# find the sum
tf.reduce_sum(S)

<tf.Tensor: shape=(), dtype=int64, numpy=2645>

In [ ]:
import tensorflow_probability as tfp
# find the veriancr and the variance is the measure of how far a set of numbers is spread out from their average value
tfp.stats.variance(S)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1363,  510, 1491,  261,  315, 1392,  522,  557,  411,  788])>

In [ ]:
# find the var throue the math lab
tf.math.reduce_variance(tf.cast(S, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=971.57>

In [ ]:
# find the standerd derviation
tf.math.reduce_std(tf.cast(S , dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.170017>

---

In [ ]:
# positional tensor
tf.random.set_seed(42)
Ten = tf.random.uniform(shape=[50]) # if we set the shape by (1,50) we will get weird reselt of argmax and argmin
Ten

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(Ten)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
Ten[tf.argmax(Ten)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.argmin(Ten)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
Ten[tf.argmin(Ten)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_max(Ten) ,"\n" ,tf.reduce_min(Ten)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 '\n',
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

----

In [ ]:
# squeezing the tensor which remove the 1 dim of tensor
tf.random.set_seed(42)
Z = tf.constant(tf.random.uniform(shape=[50]) ,shape=(1,1,1,50))
Z

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [ ]:
tf.squeeze(Z)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

----

In [ ]:
# One-hot tensor
some_list = [0,1,2,3,4]
tf.one_hot(some_list ,depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list ,depth=5 ,on_value="siii", off_value="hoo")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'siii', b'hoo', b'hoo', b'hoo', b'hoo'],
       [b'hoo', b'siii', b'hoo', b'hoo', b'hoo'],
       [b'hoo', b'hoo', b'siii', b'hoo', b'hoo'],
       [b'hoo', b'hoo', b'hoo', b'siii', b'hoo'],
       [b'hoo', b'hoo', b'hoo', b'hoo', b'siii']], dtype=object)>

-----

In [ ]:
# converting numpy array to tensor and tensor to np array
J = np.array([3,9,1,6])
J

array([3, 9, 1, 6])

In [ ]:
ggg = tf.constant(J)
ggg

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 9, 1, 6])>

In [ ]:
H = tf.constant([3,7,6,5])
H

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 7, 6, 5], dtype=int32)>

In [ ]:
H.numpy()

array([3, 7, 6, 5], dtype=int32)

----

In [ ]:
# gpu
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sun Oct 30 08:11:47 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    28W /  70W |    314MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------